## LATIHAN

## 1.Perkalian Matrix

In [2]:
import numpy as np
A = np.array([8, 9, 5])

B = np.array([4, 8, 5])

# Mengalikan matriks A dan B

kali = A * B
print(kali)


[32 72 25]


## 2.Pengurangan Matrix

In [3]:
import numpy as np

A = np.array([[0,7], [8,5]])
B = np.array([[5,5], [2,4]])

kurang = A - B
print(kurang)

[[-5  2]
 [ 6  1]]


## 3.Transpose Matrix

In [4]:
import numpy as np

A = np.array([[8,7,5],[2,3,5]])

transpose_A = np.transpose(A)
print(transpose_A)

[[8 2]
 [7 3]
 [5 5]]


## 4.Nilai Invers

In [5]:
A = np.array([[4,2], [3,3]])

inverse_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print(inverse_A)


invers matriks A:
[[ 0.5        -0.33333333]
 [-0.5         0.66666667]]


## 5.Nilai Determinan

In [6]:
import numpy as np

A = np.array([[1,2], [3,4]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: -2.0000000000000004
